### ISSUE TITLE
Ugly white border around message input box

### ISSUE THREAD

**Issue by arifogel** [caiceA/slack-black-theme#100]
**Describe the bug**
The input box on the main screen has an ugly white border all of a sudden.

**To Reproduce**
1. Open Slack desktop app.
2. Click on `#general` for current workspace
3. Observe odd white border around input box at bottom

**Expected behavior**
There should only be dark-theme elements. The border should be a dark color, or absent. There should not be left and right margins around the input box. Not sure what should happen under input box, as this is where you would see notification that another user is typing.

**Screenshots**
![weird-border-around-input-box](https://user-images.githubusercontent.com/7737874/63080917-26489000-bef7-11e9-8714-0b607a3a6d14.png)

**Desktop (please complete the following information):**
 - OS: macOS mojave and Ubuntu 18.04
 - slack-desktop 4.0.1

**Additional context**
Problem only popped up today. I don't restart slack often, so I don't know what caused it. Rolling back to an earlier version of css doesn't seem to help; so I suspect this has something to do with latest version of Slack.

**Comment by arifogel** [comment]
It looks a bit different when text has been entered:
![weird-border-around-input-box-with-entered-text](https://user-images.githubusercontent.com/7737874/63081087-90613500-bef7-11e9-8791-1c57b2f8e86e.png)

**Comment by adammartin253** [comment]
Seeing this now as well after re-running the script. Wasn't there before

**Comment by pheiduck** [comment]
Seeing this too

**Comment by pheiduck** [comment]
I think this needs to be fixed here.:

.workspace__primary_view_footer {
background-color: #222222 !important;
color: #ffffff !important;
}

**Comment by akiraah** [comment]
Was about to post this. Slack introduced a new update and the stylings got messed up?

**Comment by akiraah** [comment]
> I think this needs to be fixed here.:
> 
> .workspace__primary_view_footer {
> background-color: #222222 !important;
> color: #ffffff !important;
> }

Where would you place this? I've placed the CSS anywhere in the CSS, re-ran the shell script and restarted slack - no changes.

**Comment by pheiduck** [comment]
hm, than I don't know whats to be done there

**Comment by pheiduck** [comment]
> > I think this needs to be fixed here.:
> > .workspace__primary_view_footer {
> > background-color: #222222 !important;
> > color: #ffffff !important;
> > }
> 
> Where would you place this? I've placed the CSS anywhere in the CSS, re-ran the shell script and restarted slack - no changes.

hm, than I don't know whats to be done there

**Comment by pheiduck** [comment]
This one?.:
.p-workspace__message_pane_input {
background-color: #222222 !important;
color: #ffffff !important;
}

**Comment by JonStone904** [comment]
Seeing this as well on Catalina and in full screen view

**Comment by akiraah** [comment]
> .p-workspace__message_pane_input {

I'm afraid this hasn't made any changes either, thanks for trying to help anyways dude :P

**Comment by caiceA** [comment]
Fixed. Thank you everyone

**Comment by akiraah** [comment]
> Fixed. Thank you everyone

You've removed the dark-mode.css ? I did a pull and ran the shell script - the dark mode is no longer there.

**Comment by caiceA** [comment]
used the CSS URL from the script

**https://raw.githubusercontent.com/caiceA/slack-raw/master/slack-4**

 I don't maintain the repo CSS

**Comment by akiraah** [comment]
Thanks, I had to update the shell script manually to use that CSS url you've provided and it works!

**Comment by madnight** [comment]
If you're using the AUR package: 

`git clone https://aur.archlinux.org/slack-desktop-dark.git`

git apply

```
diff --git a/PKGBUILD b/PKGBUILD
index e6fb8b0..e058e3b 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -17,12 +17,12 @@ makedepends=('asar')
 optdepends=('gnome-keyring')
 conflicts=('slack-desktop')
 source=("https://downloads.slack-edge.com/linux_releases/${pkgname%-dark}-${pkgver}-amd64.deb"
-        "https://raw.githubusercontent.com/caiceA/slack-black-theme/master/slack-dark-mode.css"
+        "https://raw.githubusercontent.com/caiceA/slack-raw/master/slack-4"
         "darkify_slack.js"
         "${pkgname}.patch")
 noextract=("${pkgname%-dark}-${pkgver}-amd64.deb")
 sha256sums=('6277a6c3d9c1c55813ad4fe1e56702a486ab8ff36ecbef345d1794a3a644ecbc'
-            '1fef7eb3d9225b319fb9cc3e983cde532cd434beb7a68492f3c03addd7bc6029'
+            '2261adab3109f7c203b0d72fd9a5d98d60139ceb916f6f2423dc3ac7773075ba'
             '13fc4ea2c9bfd113e123a7f74375f17c17a7256d7481f9acacb466088b913418'
             'c952eb32dd59beff9fc5374853b04acde4a60ed8c39934fcd0b66829455d594d')
 
@@ -53,8 +53,8 @@ package() {
     # of our function from being commented out
     echo "" >> $file
     head -n $((lineno - 1)) darkify_slack.js >> $file
-	sed -i -e '/\\E/d' -e 's/939393/ffffff/' slack-dark-mode.css # temporary fix for 'Add Reaction' icon
-    cat slack-dark-mode.css >> $file
+	sed -i -e '/\\E/d' -e 's/939393/ffffff/' slack-4 # temporary fix for 'Add Reaction' icon
+    cat slack-4 >> $file
     tail -n +$((lineno + 1)) darkify_slack.js >> $file
 
     # Repack with the theme change
```

`makepkg -i`

**Comment by caiceA** [comment]
Sorry guys for any inconveniences 
Today morning I removed the CSS from the repo because it was merged by someone I never used that CSS for my theme I was using another ( updated ) version of CSS from my different repo. 
I added CSS ( updated version ) to this repo for old users and updated the Shell Script for the new users.  
Thank you.
