### ISSUE TITLE
Slack 4.0.1

### ISSUE THREAD

**Issue by dvaansiseelr** [caiceA/slack-black-theme#102]
for 4.0.0 version theme installing worked on Windows 10! But not for 4.0.1 version that released today.  I think it needs new install for Slack 4.0.1.

**Comment by xfinityandbeyond** [comment]
I think the issue is that formerly, automated packages were referring to this file:

https://raw.githubusercontent.com/caiceA/slack-black-theme/master/slack-dark-mode.css

However, this file no longer exists within the repo.

**Comment by tonsit** [comment]
Not sure why the CSS was removed from the main repo. I have updated my own fork to use my forks css and things are working fine.

**Comment by caiceA** [comment]
Try using this CSS URL Always. Because its better maintained and updated with lastest issued resolved. 

https://raw.githubusercontent.com/caiceA/slack-raw/master/slack-4

**Comment by tonsit** [comment]
That would be fine, but the shell script in this repo references the file. The shell script should be updated.

I'm not sure what the benefit of keeping the css in a separate repo is?

**Comment by tonsit** [comment]
https://github.com/caiceA/slack-black-theme/blob/master/slack-dark-mode.sh#L7

**Comment by xfinityandbeyond** [comment]
This issue addresses things for Arch users:

https://github.com/caiceA/slack-black-theme/issues/100#issuecomment-521620447
