### ISSUE TITLE
Missing css referenced in shell script.

### ISSUE THREAD

**Issue by tonsit** [caiceA/slack-black-theme#103]
**Describe the bug**
The shell script references a file that does not exist.

**To Reproduce**
With a clean copy of slack, run the script, and then start slack. It will not load custom CSS.

**Expected behavior**
With a clean copy of slack, run the script, and then start slack. It should be able to find the CSS to load.

**Additional context**
https://github.com/caiceA/slack-black-theme/blob/master/slack-dark-mode.sh#L7

**Comment by tonsit** [comment]
I would suggest adding the CSS back to this repository. By removing the CSS, anyone who has ran this script previously will no longer be loading the custom CSS.

Updating the shell script to use the other repository will cause people that have already used this script to have to re-run the script in order to insert the snippet a second time. Then there will be two snippets inside the changed file.

**Comment by caiceA** [comment]
I added the file back, but for the new users, I changed the path. I didn't know they are using this file path because before updating the Slack 4.0 theme i created another repo with Slack-Raw name i am always using that CSS
