### ISSUE TITLE
Highlighted mentions are overlapping the name in threads

### ISSUE THREAD

**Issue by kayran** [caiceA/slack-black-theme#104]
**Describe the bug**
When the higlighted mention are near the name, it was overlapping the name off people who mades it:

![image](https://user-images.githubusercontent.com/474481/63125958-3909a600-bf85-11e9-8e7c-be8d97166199.png)

**To Reproduce**
1. Go to some channel
2. Mention someone in the first part of message: "@someone see here"
3. See error

**Expected behavior**
Is expected the same behavior of the default theme
![image](https://user-images.githubusercontent.com/474481/63126110-8423b900-bf85-11e9-913c-f05356b3917e.png)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Version: 4.0.1

**Comment by caiceA** [comment]
i had this issue one Mac which i fixed previously you can inspect on your side i will add the CSS

**Comment by kayran** [comment]
Hi caiceA, we are having yet the trouble with mention to a group of people

![image](https://user-images.githubusercontent.com/474481/63175117-b5e65f80-c019-11e9-83bc-403cc4e3a30e.png)

See in the picture that the mention direct to me are OK(@kayran), but the mention to the group @front-end are overlapping because the background are bigger then the direct person mention's background

**Comment by caiceA** [comment]
which CSS are you using the lates Raw CSS?

**Comment by kayran** [comment]
I'm using the CSS imported by the SH at friday, end of the day

**Comment by caiceA** [comment]
you can inspect and give me CSS i will merge to resolve this issue as i don't have linux

**Comment by kayran** [comment]
Hi @caiceA, I think this problem are caused due the font change... the line height was changed?
 I only can inspect it at the Chrome Client, but in the chrome it uses the default CSS and everything are ok, how can I help you? How you made this CSS, i can help to construct the Linux Version.

**Comment by caiceA** [comment]
you can try adding this value to its class 
display:inline-block, 
height: 18px;
position:relative;
top:1pxl
