### ISSUE TITLE
Gray-on-gray in the "see all members" popup window

### ISSUE THREAD

**Issue by extesy** [caiceA/slack-black-theme#105]
**Describe the bug**
Unstyled text is displayed in the "see all members" popup window for search box and for row highlights.

**To Reproduce**
1. Go to any channel.
2. Click on "see all members" on the right side.
3. Highlight some members.

**Expected behavior**
This popup window should have a normal dark background.

**Screenshots**
![image](https://user-images.githubusercontent.com/65872/63308194-5ea8ef00-c2a6-11e9-9e23-f1444782f79c.png)

**Desktop (please complete the following information):**
 - OS: Mojave 10.14.6

**Comment by caiceA** [comment]
Slack Version?

**Comment by extesy** [comment]
@caiceA `Version 4.0.1 (App Store)`

**Comment by caiceA** [comment]
try download 4.0.2 from the website (  remove the current version )

**Comment by extesy** [comment]
@caiceA This is from 4.0.2: ![image](https://user-images.githubusercontent.com/65872/63467523-8620c880-c41a-11e9-8a42-6a66258c7074.png)

Also notice that highlight is also invisible (dark gray on dark gray).

**Comment by caiceA** [comment]
I can not see that buttom you mentioned (View All Member) all i can see is to add member under member section on the right 
I have limited  20 people but you have many 

you can inspect on your side and i will merge your css

**Comment by extesy** [comment]
You need to choose some public channel with a lot of people. Try this one: http://clojurians.net

**Comment by caiceA** [comment]
ok that helped I fixed your issue
