### ISSUE TITLE
Grey-on-grey in "All Unreads" and "Threads" tabs

### ISSUE THREAD

**Issue by obroomhall** [caiceA/slack-black-theme#106]
**Describe the bug**
Titles inside the "All Unreads" and "Threads" tabs are coloured in a dark shade of grey over a slightly lighter shade of grey, making it difficult to read.

**To Reproduce**
1. Go to "All Unreads" or "Threads"
2. See title in top left of window

**Expected behavior**
A more readable title

**Screenshots**
![image](https://user-images.githubusercontent.com/4409652/63531692-f9046f00-c500-11e9-9206-3d9cb4635003.png)

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14.6
 - Browser: Desktop client
 - Version: 4.0.2

**Comment by caiceA** [comment]
fixed you also need to install the font check  readme
