### ISSUE TITLE
Threads tab uncentered and not dark

### ISSUE THREAD

**Issue by obroomhall** [caiceA/slack-black-theme#107]
**Describe the bug**
Threads tab has a white background and the image has risen to the top of the page.

**To Reproduce**
1. Go to Threads
2. See error

**Expected behavior**
Dark background and centred logo.

**Screenshots**
![image](https://user-images.githubusercontent.com/4409652/63582638-5b0cb500-c591-11e9-8f97-2353b84638e6.png)

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14.6
 - Browser: Desktop client
 - Version: 4.0.2

**Comment by caiceA** [comment]
thank you for reporting it. 
I have fixed that
