### ISSUE TITLE
White text on white background when editing message

### ISSUE THREAD

**Issue by JacobHelton57** [caiceA/slack-black-theme#109]
When editing my own message, the message box turns white and the text is still white. The only way to see the text is to highlight it.

**To Reproduce**
1. Go to a message of yours, click more actions, and then edit message.

I'm not sure what color that dialogue box should normally be but I'm pretty sure it's not supposed to be white.

![image](https://user-images.githubusercontent.com/24308669/63602083-aecccd80-c594-11e9-96d4-3d43aed89ae8.png)

I believe this was probably due to an update. After slack updated, it got rid of all theme colors. After reinstalling the theme, I found the above mentioned issue with the edit message dialogue box.

**Desktop :**
 - OS: Mac OS X 10.14.5
 - Slack App Version 4.0.2

**Comment by JacobHelton57** [comment]
Seems some of the preferences page was also impacted. The 'My Keywords' and 'Do Not Disturb' boxes are also white on white. This is under Slack > Preferences > Notifications

![image](https://user-images.githubusercontent.com/24308669/63602802-47b01880-c596-11e9-954a-cc2f7ae7cd5b.png)

**Comment by caiceA** [comment]
@JacobHelton57  please restart your Slack

**Comment by JacobHelton57** [comment]
@caiceA I've done that numerous times. I don't think it has to do with a bad installation, I believe the newest Slack update may have changed some of the element names that the CSS was pointing at.

**Comment by caiceA** [comment]
@JacobHelton57  New changes could take some time to reflect, you will see after some time in 30 mins or so because of CSS stores in cookies sometime. you don't need to re-install anything just restart Slack after some.

**Comment by matt1981m** [comment]
I had patch slack again today due to the 4.0.2 update and was also having the edit issue, but I was able to quit slack, and open again, and that issue is fixed.  I do see that the keywords in Preferences are still showing as "white on white"... Will try to quit/reload in an hr or so if it persists

**Comment by JacobHelton57** [comment]
@caiceA, I was unaware of the delay for changes to update. After closing and reopening a couple of times, I was still having issues. 

I closed, reinstalled the theme, and re-opened and it now appears to be working. The keywords are still showing white-on-white for me, but the do not disturb is back to normal color scheme. 

I'll create a new issue if the keywords box doesn't change after some time.
