### ISSUE TITLE
Slack Channel Header Bar is White

### ISSUE THREAD

**Issue by dengsauve** [caiceA/slack-black-theme#110]
**Describe the bug**
The header bar for slack is white, and buttons are not visible.

**To Reproduce**
1. Run install script
2. Restart Slack
3. See white header

**Expected behavior**
Header bar should be dark theme as well

**Screenshots**
<img width="1536" alt="Screen Shot 2019-08-23 at 10 43 03 AM" src="https://user-images.githubusercontent.com/17308751/63612317-d458d780-c592-11e9-9741-dad6d1d660c8.png">

**Desktop (please complete the following information):**
 - OS: MacOS Mojave - Version 10.14.5
 - Slack Version 4.0.0

**Additional context**
Problem only started today. Slack refreshed itself and broke in the process.

**Comment by gumschu** [comment]
Happening for me on Slack 4.0.2, immediately after updating today.

LOVE this theme, thanks for maintaining it!

**Comment by matt1981m** [comment]
Same for me on 4.0.2 & Windows 10 (used the PS script to install).  Had the white on white issue for edits & preferences earlier, and reloading had fixed those, but the header issue persists.  I agree with @eschu21, THANK YOU for taking care of us!!

**Comment by caiceA** [comment]
thanks everyone, 
its fixed don't know what's wrong with Slack too many unwanted CSS anyways please restart

**Comment by dengsauve** [comment]
Thanks @caiceA for fixing, and for making this in the first place. I value every second that I'm not blinded by the white background.
