### ISSUE TITLE
Direct Messages: Invite another member: white on white

### ISSUE THREAD

**Issue by sishbi** [caiceA/slack-black-theme#113]
**Describe the bug**
The Direct Messages 'Invite another member' panel has white on white in the member list box.

**To Reproduce**
1. Go to 'Direct Message with at least 2 people in it'
2. Click on 'Conversation Settings button'
3. Click on 'Invite another member...'
4. See that list of members is displayed in a box with white background.

**Expected behavior**
You can see the names of the members.

**Screenshots**
<img width="718" alt="Slack_Invite_Members" src="https://user-images.githubusercontent.com/3800191/64327843-49c99c80-cfc4-11e9-9f37-ba3aee401103.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Version: 4.0.2

**Additional context**
Possible fix: 
`.c-multi_select_input--large {`
`background-color: #222222;`
`}`

**Comment by caiceA** [comment]
i added your css
thank you
