### ISSUE TITLE
Black text on black background in Organization Directory

### ISSUE THREAD

**Issue by adammartin253** [caiceA/slack-black-theme#116]
**Describe the bug**
When launching a user's profile in the right side, the info is black text on a black background

**To Reproduce**
1. Go to a user's account in a channel and click on their picture
2. Click on 'Click to View Profile'
3. See text color error below photo

**Expected behavior**
Should be white text on black background
**Screenshots**

![image](https://user-images.githubusercontent.com/25132139/64656413-31062000-d3e4-11e9-981e-52e49b3bf41c.png)

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.6 (18G95)
 - Browser: N/A
 - Version: 4.0.3

**Comment by caiceA** [comment]
@adammartin253 your baby is very cute, 
you first need to install the font ( download from Readme ) 
will resolve this issue soon 
thank you

**Comment by caiceA** [comment]
@adammartin253  are you using this repository CSS in your shell file or what is your path ?
