### ISSUE TITLE
Workspace Name Text Black/Illegible

### ISSUE THREAD

**Issue by JonStone904** [caiceA/slack-black-theme#117]
Unsure if this is with everyone or only with multiple workspaces, but the workspace name and my username in the top left is dark and illegible against the background.

![image](https://user-images.githubusercontent.com/46907262/65684531-dac4ee00-e02d-11e9-875a-0805e41b8796.png)

**Comment by JonStone904** [comment]
I'm currently in multiple workspaces. Could not confirm if happening with single workspace

**Comment by caiceA** [comment]
fixed.
