### ISSUE TITLE
Edit post background is white

### ISSUE THREAD

**Issue by dgmorrisjr** [caiceA/slack-black-theme#118]
When editing a prior post, the edit area has white background with white foreground, unable to view content to be edited.

**Expected behavior**
Background should be dark similar to the area where you write posts.

**Screenshots**
![Screen Shot 2019-09-27 at 2 09 07 PM](https://user-images.githubusercontent.com/12668108/65792294-73906200-e131-11e9-88fa-2bc16297fc59.png)

**Desktop (please complete the following information):**
 - OS: OSX
- Browser: Chrome Version 77.0.3865.90

**Comment by caiceA** [comment]
you mean browser not the desktop app?

**Comment by dgmorrisjr** [comment]
I’m using the desktop app.  I added the browser info as it was in the issue template and wasn’t sure if that had an impact I’m not aware of. 

Thanks!
Dan Morris

**Comment by caiceA** [comment]
Fixed Thank you

**Comment by dgmorrisjr** [comment]
Thank you!
