### ISSUE TITLE
Slack does not start anymore after adding the custom CSS loading code

### ISSUE THREAD

**Issue by michahell** [caiceA/slack-black-theme#12]
Hi! Love the amount of work you seem to have put into this, but Slack refuses to start after having added your custom CSS part in `ssb-interop.js` :(

**Comment by caiceA** [comment]
@michahell can you download the latest version from web ( remove the existing one ) and replace the whole ssb-interop.js instead of adding css? 
if you adding only css part into your own file you may doing it wrongly that causing an error in starting Slack

**Comment by michahell** [comment]
makes sense, using your file works.
