### ISSUE TITLE
The theme cannot be applied to Slack 4.2.0 

### ISSUE THREAD

**Issue by dmitry-minchuk** [caiceA/slack-black-theme#122]
After executing slack-dark-mode.sh nothing happens.

**Steps to reproduce the behavior:**
1. Download latest slack-dark-mode.sh
2. Set `-rwxr-xr-x@` rights for slack-dark-mode.sh
3. Run `sudo ./slack-dark-mode.sh`
4. Restart Slack

**Expected behavior:**
Custom Dark Theme has been applied

**Screenshots:**
<img width="419" alt="Screen Shot 2019-12-06 at 12 44 08" src="https://user-images.githubusercontent.com/19321365/70313166-22ce7100-1826-11ea-9b74-d0a84f87fb1d.png">

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15.1
 - npm: 6.13.2

**Comment by caiceA** [comment]
Yes. It’s because Slack has its own dark mood it’s no longer active or
fixed. I don’t like it’s default dark mood but I will fix it some day
You can use its default dark mood from slack settings

**Comment by dmitry-minchuk** [comment]
I don't like its native dark mode as well. Will be waiting updates from you...

**Comment by caiceA** [comment]
@dmitry-minchuk I don't like either
 the company I was working with, they used Slack. I don't work with them anymore and its long-time I didn't use Slack

**Comment by marshimaro** [comment]
It appears that ssb-interop.bundle.js is moved to main-preload-entry-point.bundle.js. So running slack-dark-mode.sh against that file works as previously for me.

**Comment by caiceA** [comment]
@marshimaro yes you are right i updated the Repo file Thank you
