### ISSUE TITLE
Slack 3.3.3 broke the theme

### ISSUE THREAD

**Issue by ikunali** [caiceA/slack-black-theme#13]
Theme is broken in latest slack update 3.3.3

**Comment by caiceA** [comment]
its ok on my end @TG-KK 
<img width="1918" alt="screenshot 2018-10-26 at 18 14 44" src="https://user-images.githubusercontent.com/16766231/47578976-0edded80-d94b-11e8-81f0-e15c419feadf.png">

**Comment by ikunali** [comment]
So, I tried to redo the theme install & it strangely worked! I think my copy of ssb-interop.js was old.
