### ISSUE TITLE
Looking for this style to match MacOS Mojave

### ISSUE THREAD

**Issue by mehdi9000** [caiceA/slack-black-theme#14]
https://github.com/widget-/slack-black-theme

Scroll down to "One Dark" 

which uses: 

"--primary: #61AFEF;
--text: #ABB2BF;
--background: #282C34;
--background-elevated: #3B4048;"

For some reason the lato code/version you have spaces things out more - I want to make it to look exactly like this: 

![](https://user-images.githubusercontent.com/806101/27455546-826b3d88-5752-11e7-8a6b-87285b90eb3e.png)

When I tried using https://github.com/widget-/slack-black-theme 's version on MacOS Mojave, the main chat window is white. When I use yours, all the windows correctly match in color, but the font seems too spaced out, different from Slack's default font, and doesn't match MacOS's dark mode ("One Dark" does though). 

I looked over your code for the ssb-interop.js file & I have no idea how to edit it to make it look like what you see in this image above. I just want to make it look like this with Slack's default fonts/spacing/etc.

**Comment by caiceA** [comment]
@GodofWar9000 as **I mentioned in my first step** 

Download and INSTALL this front locally to your computer first  (slack default font) https://www.fontsquirrel.com/fonts/lato 


**are you sure you are following this step?**  share you screenshot with my theme installed

I am not taking much care of original theme i just customize one from it.

**Comment by mehdi9000** [comment]
Yes, I installed the lato font. Is that the default font for Slack desktop client? 

![image](https://user-images.githubusercontent.com/9539678/48158272-1d5bcb80-e2a0-11e8-8f82-7f4da931f917.jpeg)


The "One Dark" screenshot from above is similar tot he dark mode settings of MacOS Mojave. 

It's using these settings: 

"--primary: #61AFEF;
--text: #ABB2BF;
--background: #282C34;
--background-elevated: #3B4048;"

But I wasn't able to edit your file to incorporate these properly – perhaps you know where they need to be changed to reflect it properly?

**Comment by caiceA** [comment]
i think your issue is more related to the original theme, in your latest screenshot my theme is working fine as it should. you can close this issue from here and create in original repository

**Comment by mehdi9000** [comment]
I wanted to use your theme but use those settings – how would I do that?

**Comment by caiceA** [comment]
@GodofWar9000 its a bundle of effort because it may cause some other cosmetic issues, unfortunately I don't have much time these days. what I had I shared through Repo... 
Sorry at this time 😑
