### ISSUE TITLE
Background highlight in Direct Messages search is too bright

### ISSUE THREAD

**Issue by OTLFrostA** [caiceA/slack-black-theme#15]
When starting a new direct message, slack will highlight the first matching result, which makes the text barely readable.

<img width="661" alt="screen shot 2018-12-06 at 10 59 20 am" src="https://user-images.githubusercontent.com/5652631/49605752-3bbbf200-f946-11e8-9c2f-224030e7aaf9.png">

**Comment by caiceA** [comment]
@OTLFrostA  I have fixed your concern and also, made some general cosmetic fixing. I will release a new update very soon. 



<img width="725" alt="screenshot 2018-12-25 at 14 07 46" src="https://user-images.githubusercontent.com/16766231/50422848-81395400-084e-11e9-99da-a64da3e415a4.png">

**Comment by caiceA** [comment]
Fixed Get latest file 

Thanks
