### ISSUE TITLE
All Unreads Mark as Read button contrast is very low

### ISSUE THREAD

**Issue by dylanjameswagner** [caiceA/slack-black-theme#16]
The "Mark as Read" button on the "All Unreads" view has very low contrast until you hover.

![screen shot 2018-12-28 at 09 31 32](https://user-images.githubusercontent.com/893345/50518409-74ea0c80-0a83-11e9-81cd-8d0cf83ebae5.png)

Hover

![screen shot 2018-12-28 at 09 36 01](https://user-images.githubusercontent.com/893345/50518508-022d6100-0a84-11e9-9c77-bfe390117a37.png)

---

Great work thus far, thank you for actively maintaining this.

**Comment by caiceA** [comment]
@dylanjameswagner when do you get this ?

**Comment by dylanjameswagner** [comment]
There is an "All Unreads" item for the sidebar (it may not be on by default).

![screen shot 2019-01-03 at 14 30 29](https://user-images.githubusercontent.com/893345/50657370-4cbb4b80-0f64-11e9-951f-6c6cdf9c072c.png)

![screen shot 2019-01-03 at 14 29 44](https://user-images.githubusercontent.com/893345/50657410-66f52980-0f64-11e9-897e-b1fbf7842093.png)

**Comment by caiceA** [comment]
ok i got it and fixed but will push the new update next week with other cosmetic things 

<img width="751" alt="screenshot 2019-01-03 at 21 49 02" src="https://user-images.githubusercontent.com/16766231/50660834-73e43e00-0fa1-11e9-9671-f6c2431aae5a.png">

**Comment by caiceA** [comment]
@dylanjameswagner  on **your ssb-interop.js** file 
go to **line no. 921** and add this code 

.unread_group .unread_group_header .unread_group_mark, .unread_group .unread_group_header .unread_keyboard{
        background: #339252 !important;
        color: white !important;
    }

**Comment by dylanjameswagner** [comment]
@caiceA Works for me. Thank you.
