### ISSUE TITLE
Date at top of message window is clipped

### ISSUE THREAD

**Issue by terramare** [caiceA/slack-black-theme#18]
The date straddles the message pane and the top pane, and the top half appears clipped.

I tried to get at the CSS to make a PR, but looks like the styling is inline. Do you see a way to fix this?

**Comment by caiceA** [comment]
try sharing screenshot @terramare

**Comment by caiceA** [comment]
@terramare  add this to your file and restart 

.c-message_list__day_divider__label__pill {
    background: #222 !important;
    top: 13px;
    color: white;
}
.c-message_list__day_divider__line {
    border-top-color: #363636;
    top: 13px;
}

**Comment by terramare** [comment]
Looks good. Thanks @caiceA
