### ISSUE TITLE
Theme was dropped after January slack update

### ISSUE THREAD

**Issue by ZephyrVentum** [caiceA/slack-black-theme#19]
14 January slack was updated and your theme was dropped out. Please review what is the reason. And how to return caiceA/slack-black-theme (now it unavailable to setup)

**Comment by caiceA** [comment]
@ZephyrVentum I updated my theme just now there is no problem you may need to uninstall your theme and download from Slack website latest version and then install back .JS file / download from link mentioned in the Github

**Comment by ZephyrVentum** [comment]
@caiceA Thank you!
