### ISSUE TITLE
Threaded Replies are Hard to View

### ISSUE THREAD

**Issue by ngurney** [caiceA/slack-black-theme#21]
See this screenshot: https://cl.ly/60a820321937

I am using the latest version of the file and Slack.

**Comment by caiceA** [comment]
@ngurney  did you download it from server ?

**Comment by Wiejeben** [comment]
Looks fine to me in 3.3.7

**Comment by jordan-gillard** [comment]
I am also having this problem. I'm using Slack version 3.3.6 and copied the ssb-interop.js file today.

**Comment by caiceA** [comment]
@Jordan-Gillard attach clear screenshot

**Comment by jordan-gillard** [comment]
![screenshot 2019-01-22 at 11 49 58](https://user-images.githubusercontent.com/20758755/51530735-eaa38700-1e3b-11e9-89e5-4155fcc25cfe.png)

**Comment by caiceA** [comment]
@Jordan-Gillard its strange your theme is not like the one uploaded 
can you remove your slack and install the new version from Slack Website and then replace my file because my theme has different username color, Time and date color etc 
<img width="488" alt="screenshot 2019-01-22 at 11 55 34" src="https://user-images.githubusercontent.com/16766231/51531050-b086b500-1e3c-11e9-8dc8-1c120d5e93d2.png">


Try downloading the Slack 3.3.7 lastest version **BETA**

**Comment by jordan-gillard** [comment]
Names appear like yours in all other windows except the thread one. This is a better view: 
![screenshot 2019-01-22 at 13 14 13](https://user-images.githubusercontent.com/20758755/51535024-a8804280-1e47-11e9-93d6-3501066472b4.png)

**Comment by caiceA** [comment]
i will cross check but please download the file from this link
https://foxshift.com/slack-lato-font/ssb-interop.js.zip 
and replace with yours, i don't see any issue at the moment on my side. 

<img width="1224" alt="screenshot 2019-01-22 at 13 22 45" src="https://user-images.githubusercontent.com/16766231/51535508-f0ec3000-1e48-11e9-8b1c-3eafa0700563.png">

**Comment by jordan-gillard** [comment]
I still have the issue after replacing the file. It's okay, this isn't a very pressing issue. Thanks for trying to help!

**Comment by Column01** [comment]
I also have this issue, Just reinstalled using the latest version and it is still present. Also appears to be set to a dark color in the JS. Maybe slack changed their method for the reply bar?
EDIT:
Tested in beta version 3.3.7 and it is still not working properly.
![img](https://i.imgur.com/FBl50Om.png)

**Comment by Column01** [comment]
Also appears to be set to a dark color in the JS. Maybe slack changed their method for the reply bar?

**Comment by caiceA** [comment]
@Column01 @Jordan-Gillard  i don't know where is the problem i just re-installed and its working fine on my side 
https://www.youtube.com/watch?v=NmD6FrgmpjE&feature=youtu.be 
sorry about the video quality

**Comment by Column01** [comment]
You're on mac, that might be why. I'm on Windows

**Comment by caiceA** [comment]
oh my Gosh, 
i wrote in the title **Mac Only** 

but i can help you in fixing it in windows too but for that easy way is you have to give me access through TeamViewer. up 2 u. 

thanks 

<img width="1009" alt="screenshot 2019-01-22 at 19 43 48" src="https://user-images.githubusercontent.com/16766231/51557762-18112480-1e7e-11e9-87ba-bdd288ef02db.png">

**Comment by jordan-gillard** [comment]
I'm on mac as well.

**Comment by ngurney** [comment]
Yeah, I am on a mac and I am having the issue. I downloaded the latest file just before opening this ticket. Any other ideas? I can reinstall slack but it sounds like that didn't work.

**Comment by caiceA** [comment]
@ngurney its strange give me couple of days i will push new update hopefully that will resolve it.

**Comment by Column01** [comment]
I mean its JS so it shouldn't matter for OS... Ill wait for the update

**Comment by caiceA** [comment]
@Jordan-Gillard @ngurney issue fixed, please get the latest file from the repository or download from the server. 

@Column01  you can try new file if that works. 


Thanks,

**Comment by jordan-gillard** [comment]
Works perfect! Thanks @caiceA :)

**Comment by caiceA** [comment]
few things will be fixed in next release maybe next month !! thanks everyone

**Comment by Column01** [comment]
Looks better now, but the text in the reply bar before you type is still dark.
Comparison:
![Threaded Reply](https://i.imgur.com/wKoZdR1.png)
![Normal Reply](https://i.imgur.com/2cVfUoS.png)

**Comment by caiceA** [comment]
@Column01 i know it will be fixed next time

**Comment by caiceA** [comment]
@Column01 fixed somehow download the new version
