### ISSUE TITLE
Can't customize name colours.

### ISSUE THREAD

**Issue by KraegM** [caiceA/slack-black-theme#22]
I'm unable to customize my name colour or the name colour of other users so there's no visual contrast from one name to another. All are in a default white. Any thoughts?
![screen shot 2019-01-21 at 10 09 36 am](https://user-images.githubusercontent.com/26904784/51491941-cfb21380-1d64-11e9-91fa-63b7cd746536.png)

**Comment by caiceA** [comment]
what kind of color you need in my theme its green color 
<img width="190" alt="screenshot 2019-01-21 at 19 30 53" src="https://user-images.githubusercontent.com/16766231/51492721-1595c880-1db3-11e9-9212-d124ddf44f89.png">

**Comment by KraegM** [comment]
Sorry CaiceA, I don't think I explained it correctly. I don't seem to be able to customize name colours. I use the command /color @myname #f26522 but nothing changes. In your example where your name is in green as part of the theme, mine just shows up as white.

**Comment by caiceA** [comment]
@KraegM it won't work like this you have to change that class (color property) to set your own color ( in your current file ) 
what color you need

**Comment by KraegM** [comment]
#36b575
______________________________________

On Jan 21, 2019, at 12:28 PM, CacieA <notifications@github.com<mailto:notifications@github.com>> wrote:


@KraegM<https://github.com/KraegM> it won't work like this you have to change that class (color property) to set your own color ( in your current file )
what color you need

**Comment by caiceA** [comment]
<img width="162" alt="screenshot 2019-01-22 at 10 41 08" src="https://user-images.githubusercontent.com/16766231/51526265-449f4f00-1e32-11e9-883a-f7d8758e130b.png">
@KraegM it would be like this but you can do it on your side in your file

**Comment by KraegM** [comment]
Thanks @caiceA, that worked. I didn't realize i'd have to manually edit the code. Much appreciated, and thank you for the dark mode.
