### ISSUE TITLE
Anyway to pull css from this repo?

### ISSUE THREAD

**Issue by jcpeterson** [caiceA/slack-black-theme#23]
Some other themes pull directly from their repo url as a form of autoupdate. I know you edit the js file more than most, but is this still possible?

**Comment by caiceA** [comment]
@jcpeterson in next release I will do that! ... Good suggestion! 
just pushed the latest changes you can use the newer version
thanks

**Comment by jcpeterson** [comment]
Great, thanks!

**Comment by ikunali** [comment]
I believe this can be closed as for Slack 4, the script pulls css from repo directly.
