### ISSUE TITLE
Threaded reply header: channel name is invisible

### ISSUE THREAD

**Issue by ikunali** [caiceA/slack-black-theme#25]
In threaded reply pane, channel name is invisible/blended, under `Thread` heading:
Usually a channel name is displayed there.

<img width="453" alt="image" src="https://user-images.githubusercontent.com/6836944/52069149-c0d91700-2543-11e9-896d-0ddd4de8f454.png">

**Comment by caiceA** [comment]
@TG-KK  
i thought earlier there was something missing. but yes you are right. please download from server / link i fixed that
