### ISSUE TITLE
Change title bar to black

### ISSUE THREAD

**Issue by cristeaadrian** [caiceA/slack-black-theme#26]
First of all, congrats on this theme, it's by far the best I've found so far. It's possible I misunderstood some step, but while most of the colours do change to grey, the title bar remains the usual white, regardless of the number of workspaces I'm signed into. I'm guessing it's an issue with the latest update.

![screenshot 2019-02-01 at 09 59 47](https://user-images.githubusercontent.com/9112724/52116256-9dc46b00-2608-11e9-8dfc-756e03689f3c.png)

Is there anything that can be done about it?

**Comment by caiceA** [comment]
@cristeaadrian you need to restart your computer / Slack maybe, I don't think its in my hand, If you have only one team in slack, this bar appears but when you have multiple teams added to your slack it automatically goes. that's what i noticed months ago. 

<img width="1396" alt="screenshot 2019-02-01 at 11 08 49" src="https://user-images.githubusercontent.com/16766231/52116964-d36e5180-2612-11e9-8fa2-c660e36fc25f.png">

**Comment by caiceA** [comment]
Under your sidebar settings, you need to make it dark too from your side -- just in case 


<img width="319" alt="screenshot 2019-02-01 at 11 18 23" src="https://user-images.githubusercontent.com/16766231/52117077-1af4dd80-2613-11e9-8bd4-0f6f2c5a1c1a.png">

**Comment by cristeaadrian** [comment]
You're right, I had to restart after adding a second workspace, and then it disappears. I'm assuming correctly that there's no way to force slack to show the workspace switcher view, without you actually having multiple workspaces?

God, I hate Electron apps 🙄 

In any case, thanks a lot!

**Comment by caiceA** [comment]
i don't like anything !!!
