### ISSUE TITLE
The send button is out of alignment

### ISSUE THREAD

**Issue by brwnj** [caiceA/slack-black-theme#28]
<img width="599" alt="screen shot 2019-02-21 at 4 30 48 pm" src="https://user-images.githubusercontent.com/786366/53209004-3d688e00-35f6-11e9-804e-3d5fbd6bb77a.png">

**Comment by caiceA** [comment]
@brwnj can you explain when you see this ?

**Comment by brwnj** [comment]
I use the setting under Preferences/Advanced/Show send button to send messages because I hate trying to remember shift-enter for line breaks. Then this will show on any group where you can send a message.

For a temporary fix, I just commented out everything under font-weight in your button definition:
```
.btn {
    background: #008952;
    color: #fff;
    line-height: 1.2rem;
    font-weight: 900;
    // -webkit-user-select: none;
    // -moz-user-select: none;
    // -ms-user-select: none;
    // user-select: none;
    // text-decoration: none;
    // cursor: pointer;
    // text-shadow: 0 1px 1px rgba(0, 0, 0, .1);
    // border: none;
    // border-radius: .25rem;
    // box-shadow: none;
    // position: relative;
    // display: inline-block;
    // vertical-align: bottom;
    // text-align: center;
    // white-space: nowrap;
    // margin: 0;
    // -webkit-appearance: none;
    // -webkit-tap-highlight-color: transparent;
}

```

**Comment by caiceA** [comment]
if you comment only Margin property it would solve this issue, normally its not in use for mostly users so i didn't check this button thing
i have fixed for other users
