### ISSUE TITLE
maybe make text-color for image uploads a little brighter? 

### ISSUE THREAD

**Issue by chuyaguo2014** [caiceA/slack-black-theme#29]
I noticed that when I upload an image in slack, the texts that include the timestamp of the image upload are a little hard to read. 

Here's what I mean:

![image](https://user-images.githubusercontent.com/9753313/53273973-a0742680-36c3-11e9-80cf-f9c1cb834638.png)

I manually highlighted the text to make them more visible in this screenshot. 

![image](https://user-images.githubusercontent.com/9753313/53274007-ba156e00-36c3-11e9-9750-51df4f2fc5ff.png)

I am using Mac Mojave and my slack version is 3.3.7. 

Everything else about this theme is awesome though! This is by far my favorite! :) thanks for the good work! 👍

**Comment by caiceA** [comment]
@chuyaguo2014 thank you. 

I have fixed this get file from server again,

**Comment by chuyaguo2014** [comment]
yup it is working now! thank you so much! 👍
