### ISSUE TITLE
Alternate Font recommendation?

### ISSUE THREAD

**Issue by jonahx** [caiceA/slack-black-theme#3]
Hi @caiceA,

Thanks for making this.  I love the theme.  My only small nitpick is that I'd like a more traditional font for the text of the actual messages people type.  Can you recommend an alternative font that fits the bill, and the CSS selector I'd need to change?

Thanks!

**Comment by caiceA** [comment]
@jonahx i will create some font options next week do you have any preference related to the font?

**Comment by jonahx** [comment]
I don't have a great eye for font matching, and your font _looks_ good, but I can tell you conceptually the problems I see:

1. Not compact enough.  The letter-spacing seems to wide for normal content text.  Less text fits on a screen.
2. Not enough contrast between the font of the poster's name, and the font of the message.  This makes name scanning subtly harder.

Compare with default slack:
![image](https://user-images.githubusercontent.com/699684/45245405-36f58c80-b2ca-11e8-9e0a-23ed32a17c70.png)

**Comment by caiceA** [comment]
@jonahx get the latest from repo or download from the server,  i hope that will solve your above request !!
have a great weekend!!!

**Comment by jonahx** [comment]
Really appreciate it!  You too!
