### ISSUE TITLE
Crashed: Update 3.3.8

### ISSUE THREAD

**Issue by SiimonStark** [caiceA/slack-black-theme#31]
Just updated and lost the theme. I tried going through the installation instructions again, and no use.

**Comment by chuyaguo2014** [comment]
I actually went through the update to Slack 3.3.8 earlier this morning as well and was able to get the dark theme working with no problem following the same installation instructions. I'm on MacOS Mojave 10.14.3. 

Maybe post some screenshots of the errors you are seeing will help diagnose the issue?

**Comment by SiimonStark** [comment]
I'll double check the installation instructions then, I may have missed a step. 
Sorry

**Comment by SiimonStark** [comment]
If I run into issues again, I'll post the screenshots.
