### ISSUE TITLE
Github Release

### ISSUE THREAD

**Issue by umarrasydan** [caiceA/slack-black-theme#35]
Wanna give appreciation to the author @caiceA for making this amazing theme, it's super slick. If it's not too much of an ask, when you do an update to the theme, I would very much appreciate if you could create a github release tag. 

This way I can simply watch for releases and get notified when you update 👍

**Comment by caiceA** [comment]
@umarrasydan thanks will do that i pushed some commit these month but from next month i will add tags and less commits
