### ISSUE TITLE
please turn off capitalization

### ISSUE THREAD

**Issue by casalefornia** [caiceA/slack-black-theme#37]
https://github.com/caiceA/slack-black-theme/blob/master/ssb-interop.js#L131

this line causes all names to be capitalized, which ignores usernames that are lowercase.
is this a stylistic choice? i change this line every time i update manually.

**Comment by caiceA** [comment]
@casalefornia ok I removed this, one of my team members had some naming issue so I made it for myself, 
latest file is on the server but you don't need to get it if you have made a change on your side.
