### ISSUE TITLE
Readme info

### ISSUE THREAD

**Issue by r3dshell** [caiceA/slack-black-theme#39]
The readme mentions it works for Mac Only, however I can confirm it works on Linux as well. 

When Slack is installed locally, the path of the js file to replace is:

`/usr/lib/slack/resources/app.asar.unpacked/src/static/ssb-interop.js`

**Comment by caiceA** [comment]
@depelteau  thanks for your info but i have Mac so i tested on mac only, couldn't check on other OS

**Comment by caiceA** [comment]
I will remove " Mac Only "
