### ISSUE TITLE
White bits in the Downloads area

### ISSUE THREAD

**Issue by kohlo** [caiceA/slack-black-theme#4]
Hey there! 

First off, thanks so much for this awesome theme, it's very complete and so easy on the eyes! There's just one small bit that stays (partly) white, in the Downloads tab:
![image](https://user-images.githubusercontent.com/43231411/45471404-442ed300-b731-11e8-8f85-6de330abc7fc.png)
So the bottom Shift-click hint, and the hover mode are white. I'd really appreciate it if you could help me with this, since I usually have that tab open. 

Thanks again!

**Comment by caiceA** [comment]
@kohlo  you can wait for next release will do improvements and cosmetic issues fixing

**Comment by caiceA** [comment]
@kohlo  its fixed please download the latest zip file and replaced
