### ISSUE TITLE
`Join Channel` pop-up is not dark themed

### ISSUE THREAD

**Issue by chrislan815** [caiceA/slack-black-theme#42]
![image](https://user-images.githubusercontent.com/23533430/57006328-a3dcd000-6b94-11e9-961f-6dfb6bfa4776.png)

To recreate, join a channel and you should see the join popup is not dark themed.

Slack version: Version 3.4.0 (Direct Download)

**Comment by caiceA** [comment]
@chrislan815 i don't have any channel to join/rejoin now but will fix this in a new update after some time. 

Thanks

**Comment by caiceA** [comment]
@chrislan815 
Fixed. 
Get file from the server 
Thanks
