### ISSUE TITLE
'Direct Messages' Delete Still 

### ISSUE THREAD

**Issue by ashort96** [caiceA/slack-black-theme#43]
![image](https://user-images.githubusercontent.com/16170180/57874860-8720d900-77df-11e9-8372-998bb0dbddad.png)

The 'x' by someone's name still highlights the selection in dark purple. Not a huge issue, just letting you know about this.

Using Slack version 3.4.1.

**Comment by caiceA** [comment]
you need to go to your  Preference > Side Bar > Menu BG Hover it will solve your issue
