### ISSUE TITLE
Code block background/foreground in a post is wrong color

### ISSUE THREAD

**Issue by thom-nic** [caiceA/slack-black-theme#44]
Create a post, with a code block. Pin it to the channel. Then open that post in the sidebar.  This is what I see after updating your theme today:
![Screen Shot 2019-05-24 at 11 23 10 AM](https://user-images.githubusercontent.com/95562/58338739-557ac400-7e16-11e9-9b3c-cf4bb5d65488.png)

**Edit:** Noticed the white-on-white appears in the sidebar *and* the inline preview if you view a post right in the chat thread after posting it.

PS: thank you for maintaining this theme!  I like it much better than the one by Widget- and various forks of it.

**Comment by caiceA** [comment]
@thom-nic i can't find it do a little video if possible because i tried its fine on my side

**Comment by thom-nic** [comment]
I found the issue today (so it still exists in `master` as of caiceA/slack-raw@73eb4ea)

I had to add the following to `customCustomCSS`:
```
.c-pillow_file__post__content code, 
.c-pillow_file__post__content pre,
.c-pillow_file__post__content ul.checklist {
    background: black;
}
```

To figure this out I had to find the magic `SLACK_DEVELOPER_MENU=TRUE` option. If you add this to the documentation it may help people figure out issues when reporting.

**Comment by caiceA** [comment]
@thom-nic i added it, you can restart you slack
