### ISSUE TITLE
Thema disappears after update 

### ISSUE THREAD

**Issue by M0bi0us0ne** [caiceA/slack-black-theme#45]
the theme disappeared after the last update 3.4.2 (downloaded from the Apple Store)

**Comment by caiceA** [comment]
@M0bi0us0ne i noticed that too, 

You can reinstall or just add this code at the bottom of your **ssb-interop.js**

// Slack Night Mood theme
document.addEventListener("DOMContentLoaded", function() {
    // Then get its webviews
    let webviews = document.querySelectorAll(".TeamView webview");
    // Fetch our CSS in parallel ahead of time
    const cssPath = 'https://raw.githubusercontent.com/caiceA/slack-raw/master/css';
    const localCssPath = 'sib.css';
    let cssPromise = fetch(cssPath).then(response => response.text());

    let customCustomCSS = `
`
// $("div").each(function(){

// 	$this.css("color","white");
// });
    // Insert a style tag into the wrapper view
    cssPromise.then(css => {
        let s = document.createElement('style');
        s.type = 'text/css';
        s.innerHTML = css + customCustomCSS;
        document.head.appendChild(s);
    });
    // Wait for each webview to load
    webviews.forEach(webview => {
        webview.addEventListener('ipc-message', message => {
            if (message.channel == 'didFinishLoading')
            // Finally add the CSS into the webview
                cssPromise.then(css => {
                let script = `
let s = document.createElement('style');
s.type = 'text/css';
s.id = 'slack-custom-css';
s.innerHTML = \`${css + customCustomCSS}\`;
document.head.appendChild(s);
`
                webview.executeJavaScript(script);
            })
        });
    });
});
