### ISSUE TITLE
Hovering channels and DMs makes the name invisible

### ISSUE THREAD

**Issue by Column01** [caiceA/slack-black-theme#46]
If you hover over a channel or DM it will make the name of it invisible. For example, this is Slackbot:
![img](https://i.imgur.com/Gh6LSpN.png)

**Comment by Column01** [comment]
I believe the CSS for it is `.p-channel_sidebar__link:hover` and/or `.p-channel_sidebar__channel:hover`. Should just change it to match the background color on hover probably

**Comment by caiceA** [comment]
@Column01  you need to make this change from your Preference > Side Bar color

**Comment by Column01** [comment]
You're right. My bad! Thanks.
