### ISSUE TITLE
Poor contrast in code snippets

### ISSUE THREAD

**Issue by ACSchil** [caiceA/slack-black-theme#48]
Below is a screenshot of how javascript is styled within a code snippet:

![Screen Shot 2019-06-27 at 10 56 17 AM](https://user-images.githubusercontent.com/8929887/60281713-10412a80-98cb-11e9-8259-aac072eb42f4.png)

JSON is pretty bad too with a deep reds and blues for text colors.

**Comment by caiceA** [comment]
Restart your slack.
