### ISSUE TITLE
"Loading" message box white when scrolling up

### ISSUE THREAD

**Issue by jcpeterson** [caiceA/slack-black-theme#49]
Can't take screenshot because it happens too quickly

**Comment by jcpeterson** [comment]
got it

![image](https://user-images.githubusercontent.com/8072691/60379465-2bae5180-9a01-11e9-9951-3365239f25c3.png)

**Comment by jcpeterson** [comment]
Why closed?

**Comment by caiceA** [comment]
its not doable ATM

**Comment by jcpeterson** [comment]
Not to bother, but I'll just note that I posted this issue on another theme on GitHub and it was fixed. I would link it but issues were turned off on the repo :/

**Comment by caiceA** [comment]
@jcpeterson  I don't even see this issue on my side which version are you using? get the latest one

**Comment by jcpeterson** [comment]
I have the latest and I'm on Windows. Could it be a cache issue?

**Comment by caiceA** [comment]
@jcpeterson I have mac and I don't see this issue on my side 
contact https://gist.github.com/Column01 
he runs / tests on windows he can tell

**Comment by jcpeterson** [comment]
ok thanks

**Comment by Column01** [comment]
Hey there! I have not experienced this behavior before when using it recently.
Please try the following:
- Remove the file from slack and using the installer for windows from the README (if you used the windows store to install slack, it won't work. Still working on updating it for that)
- Close slack, restart your computer and check again

Let me know if this helps.

**Comment by caiceA** [comment]
@jcpeterson

**Comment by huseyinorer** [comment]
> Hey there! I have not experienced this behavior before when using it recently.
> Please try the following:
> 
> * Remove the file from slack and using the installer for windows from the README (if you used the windows store to install slack, it won't work. Still working on updating it for that)
> * Close slack, restart your computer and check again
> 
> Let me know if this helps.

I tried it, not worked for me.

**Comment by caiceA** [comment]
@Column01

**Comment by Column01** [comment]
Hmm. I noticed yesterday that I am also getting this. It's really hard to debug the cause and find the CSS that controls that since it happens so quickly. I'm willing to go out on a limb here and say its so brief its not worth fixing but I will try to track it down when I'm free. Very busy lately dealing with life stuff so it may be a bit.

**Comment by jcpeterson** [comment]
It's worse when connection is slow. Another issue is the mouseover icon for
adding a reaction to a message (it's mostly solid white instead of showing
the emoji face icon).

I've noticed all themes break on nearly every slack release. It may be just
worth waiting for the official dark theme coming soon (mobile is already
out).

**Comment by caiceA** [comment]
@jcpeterson I cannot fix your issue because the theme originally is for Mac OS and it works fine. I don't run on windows

you can wait for the official release

**Comment by jcpeterson** [comment]
No prob. Thanks
