### ISSUE TITLE
Could you provide a version with the default font?

### ISSUE THREAD

**Issue by tschannik** [caiceA/slack-black-theme#5]
Thanks for the theme! I love everything exept the font

**Comment by brocococonut** [comment]
I personally just changed it to Roboto... It's cleaner.

**Comment by caiceA** [comment]
i **HATE** Roboto 
but i will update with more new and better fonts...very soon

**Comment by caiceA** [comment]
@yzimmermann download and install this default Slack font from here better than Roboto 

https://www.fontsquirrel.com/fonts/lato 

Replace this file with your current one.
https://foxshift.com/slack-lato-font/ssb-interop.js

**Comment by tschannik** [comment]
Thanks! I get a 404 when i try to access this url https://foxshift.com/slack-lato-font/ssb-interop.js

**Comment by caiceA** [comment]
> Thanks! I get a 404 when i try to access this url https://foxshift.com/slack-lato-font/ssb-interop.js.zip

i forgot to add.zip at the end @yzimmermann lol
