### ISSUE TITLE
Loading history white background.

### ISSUE THREAD

**Issue by huseyinorer** [caiceA/slack-black-theme#51]
![image](https://user-images.githubusercontent.com/5655614/60516814-28f47a80-9ce7-11e9-97fd-8b5b9f4c253c.png)

'Loading history's bar background is white ,How can i fix it ?

**Comment by caiceA** [comment]
windows or mac?

**Comment by huseyinorer** [comment]
Sorry, its windows 10.

**Comment by caiceA** [comment]
[You can see this issue](https://github.com/caiceA/slack-black-theme/issues/49)

**Comment by huseyinorer** [comment]
Thanks. I can fallow there.
