### ISSUE TITLE
Mac: Activity sidebar has black on black text.

### ISSUE THREAD

**Issue by luv2dnce33** [caiceA/slack-black-theme#52]
<img width="421" alt="Screen Shot 2019-07-02 at 11 46 23 PM" src="https://user-images.githubusercontent.com/43563358/60569251-b8b81a00-9d23-11e9-9ef1-ff8a353a6dd0.png">
<img width="421" alt="Screen Shot 2019-07-02 at 11 46 48 PM" src="https://user-images.githubusercontent.com/43563358/60569252-b8b81a00-9d23-11e9-861f-21bcf956c791.png">

**Comment by caiceA** [comment]
@luv2dnce33 my activity data is not this type its mentions and comments even if i use the filters / select box from top

**Comment by luv2dnce33** [comment]
As is mine, that is a highlight for example. I intentionally looked for something that was not revealing of any sensitive info.

**Comment by luv2dnce33** [comment]
Same problem with 'Unread Messages' section
<img width="819" alt="Screen Shot 2019-07-03 at 12 50 38 AM" src="https://user-images.githubusercontent.com/43563358/60573615-d8077500-9d2c-11e9-8329-4a33f2b6fda8.png">

**Comment by caiceA** [comment]
@luv2dnce33 i don't see anything on myside for now if i found in upcoming days i will fix it

**Comment by luv2dnce33** [comment]
You're right. After deleting and reinstalling the app and .js, it works just fine.
