### ISSUE TITLE
Slack 4.0.0 update changes where CSS files are

### ISSUE THREAD

**Issue by hakyn** [caiceA/slack-black-theme#54]
Ssb-interop.js doesn't exist anymore 🥺

**Comment by caiceA** [comment]
I am using Slack 4 ( beta ) for Mac and fixed this, Theme is Up and back now. thanks for [Kevin](https://github.com/smitt04)
simply drag and drop this .sh  file in your terminal, it will ask your password once done just restart Slack. 

> It requires you have **nodejs** and the **asar** package installed globally with (**sudo** at start in case) npm i -g asar

[slack-dark-mode.sh.zip](https://github.com/caiceA/slack-black-theme/files/3393293/slack-dark-mode.sh.zip)

**Comment by M0bi0us0ne** [comment]
after dropping it in terminal and insetting the password I get this message:
sudo: npx: command not found
what do I need to do?

**Comment by caiceA** [comment]
first run this command(s)

npm i -g asar

Or 

Sudo npm i -g asar

Then drag and drop

**Comment by Vyraal1** [comment]
Does this fix also work for the windows version?

**Comment by caiceA** [comment]
@Vyraal1 i don't use windows so never tried but contact **Column** [Here](https://gist.github.com/Column01/de3275e1e81356be0f2880179eb9c8c9#gistcomment-2970855)

he deals with windows i didn't make this theme for windows but sometimes it works but I have no words

**Comment by Column01** [comment]
@Vyraal1 ~~Unfortunately I cannot find a new location to inject CSS for the latest version, nor do I have the knowledge to make a workaround like above for windows. Us windows users are going to have to wait for slack to release their own theme (I'm going to keep trying to find a way to get it to work, but I can't promise anything).~~
Edit: Looks like the Shell script should work for windows now. Updated within the last 24 hours to support us! Going to try it now [here](https://github.com/smitt04/slack-dark-theme)
