### ISSUE TITLE
the src directory is not present in the slack 4.0 rls for mac

### ISSUE THREAD

**Issue by gabriel-iz** [caiceA/slack-black-theme#55]
I had this installed, and an update to slack was installed (bringing me to 4.0) afterwards the src dir was gone. I had to download slack 3.4.2 to reinstall the theme. An install update may be needed.

**Comment by caiceA** [comment]
If you download beta version 4 directly from the website then you need to run the .sh zip file attached in the previous issue 

If you using windows the theme is not for your slack 4

**Comment by gabriel-iz** [comment]
This is on mac. I am unsure of where I got slack originally. I think it was a web download. Does the web download version get autoupdated?

If you are referring to issue 54, can you point to it, I dont know how to find other issues.

**Comment by gabriel-iz** [comment]
Nvm I found the other issues, and the .sh. Might be worth updating the front page install instructions with that info.

**Comment by caiceA** [comment]
this issue is coming for Slack 4 Beta, once its officially updated i will update the readme
