### ISSUE TITLE
slack 4.0.0 has different directory

### ISSUE THREAD

**Issue by M0bi0us0ne** [caiceA/slack-black-theme#56]
after updating to 4.0.0 the directory has changed, I dropped the .sh on terminal as previously mentioned but I get this message:
sudo: npx: command not found
what do I need to do?

**Comment by caiceA** [comment]
npm i -g asar

Or

Sudo npm i -g asar

Then drag and drop

**Comment by M0bi0us0ne** [comment]
I get this 
<img width="564" alt="Screen Shot 2019-07-15 at 22 48 50" src="https://user-images.githubusercontent.com/51322421/61248211-ebfe9e00-a752-11e9-855c-b65fa69e3970.png">

**Comment by caiceA** [comment]
Try installing npm first sir

**Comment by M0bi0us0ne** [comment]
how do I do that?

**Comment by caiceA** [comment]
npm install -g 
Or 
Sudo npm install -g
Run any of these command

**Comment by M0bi0us0ne** [comment]
if I run npm install -g nothing happens, if I run Sudo npm install -g it asks for my password and after it shows Sudo: npm: command not found

**Comment by caiceA** [comment]
try this sudo apt-get install npm

**Comment by M0bi0us0ne** [comment]
nope I still get sudo: apt-get: command not found

**Comment by M0bi0us0ne** [comment]
is there any other way to get npm?

**Comment by caiceA** [comment]
these steps should work 
sudo $ brew update
sudo $ brew uninstall node
sudo $ brew install node
sudo $ brew postinstall 

if not then you need to find your issue one google

**Comment by caiceA** [comment]
you need to install Node Too 

https://blog.teamtreehouse.com/install-node-js-npm-mac

**Comment by M0bi0us0ne** [comment]
sudo $ brew update I get sudo: $: command not found

**Comment by caiceA** [comment]
start with this 

sudo $ brew install node
sudo $ brew postinstall

**Comment by caiceA** [comment]
once you install Node, Npm then uses drag and drop sh because the issue you are raising is not theme related its your computer related
I closed this issue 
thanks

**Comment by M0bi0us0ne** [comment]
thanks for the help

**Comment by M0bi0us0ne** [comment]
IT WORKED!!!!

**Comment by caiceA** [comment]
congratulation
