### ISSUE TITLE
Top channel nav is white on slack 4

### ISSUE THREAD

**Issue by ikunali** [caiceA/slack-black-theme#59]
And even some top part of right side nav as well.

**Comment by ikunali** [comment]
`All Unreads` & `Threads` top nav are white too

**Comment by caiceA** [comment]
@TG-KK can you re install your slack again, becuase these issues i fixed last day when i used 4 first time

**Comment by ikunali** [comment]
Even re-install didn't changed anything. I finally did Reset App Data & then it looked better. That was weird.
