### ISSUE TITLE
Add uninstall instructions to README?

### ISSUE THREAD

**Issue by bcuadrado** [caiceA/slack-black-theme#60]
Could uninstallation instructions be added to the ReadMe? I am looking to uninstall and reinstall my theme.

**Comment by caiceA** [comment]
I don't know,,, just remove slack and reinstall if you find a way let me know

**Comment by bcuadrado** [comment]
@caiceA I had to manually remove the lines from `ssb-interop.bundle.js` and run `sudo npx asar pack ${SLACK_RESOURCES_DIR}/app.asar.unpacked ${SLACK_RESOURCES_DIR}/app.asar`.

Since the file is originally all on one line, you may be able to make a (somewhat hacky) solution to uninstall by removing everything on lines 3+.

Another hacky solution may be to split by newline and delete all but the first two lines.
