### ISSUE TITLE
Windows hack for v4 coming soon?

### ISSUE THREAD

**Issue by JOY** [caiceA/slack-black-theme#61]
Do you plan to have the hack for v4 soon?

**Comment by caiceA** [comment]
You already have windows solutions here you can install it from here

https://github.com/widget-/slack-black-theme/issues/98#issuecomment-511973186

**Comment by caiceA** [comment]
@LeGiangAnh  they are using my Styling you can use this theme by running that script into your computer for windows

**Comment by JOY** [comment]
It doesn't work but thank you anyways.

**Comment by caiceA** [comment]
@LeGiangAnh i have mac never used windows so i am sorry at this time you better get mac lol
