### ISSUE TITLE
White header in fullscreen mode

### ISSUE THREAD

**Issue by natpuncher** [caiceA/slack-black-theme#63]
![Screen Shot 2019-07-17 at 13 00 55](https://user-images.githubusercontent.com/4374121/61367058-8c5bdc00-a893-11e9-95de-d749d49b3b78.png)

The header is white only in fullscreen mode
macOS 10.14.5, slack 4.0.0

**Comment by caiceA** [comment]
@no0bsprey fixed restart your slack

**Comment by JonStone904** [comment]
@caiceA Header is no longer white but now the channel name is black and illegible against dark background
<img width="167" alt="image" src="https://user-images.githubusercontent.com/46907262/61368233-6fa3b200-a85b-11e9-81a3-cae9eb8abbc7.png">
