### ISSUE TITLE
Danger style attachments are whitespace

### ISSUE THREAD

**Issue by JonStone904** [caiceA/slack-black-theme#66]
<img width="431" alt="image" src="https://user-images.githubusercontent.com/46907262/61398341-cfb94900-a899-11e9-95c7-e7358931a6fb.png">

when viewing attachments that use style: danger, the button appears to just be whitespace instead of red outline/text as expected

**Comment by caiceA** [comment]
@jonstonecinc i don't have any experience like this if you have css let me know

**Comment by deniskrumko** [comment]
+1

Same issue

![image](https://user-images.githubusercontent.com/7268848/61795523-4622f180-ae2c-11e9-8ecb-32a1784189f9.png)

**Comment by caiceA** [comment]
You guys should tell me which app you used and try to share some proper Img so I can see the app I use only trello with slack, I need to see the apps so I can check them

**Comment by JonStone904** [comment]
The app I use is custom built that I made myself. I’ll try and get you some css shortly

**Comment by JonStone904** [comment]
Here is CSS being returned that is showing up as whitespace
`        {
          "id": "3",
          "name": "slackPole",
          "text": "Delete Pole",
          "type": "button",
          "value": "danger",
          "style": "danger",
          "confirm": {
            "text": "Are you sure you want to delete your pole?",
            "title": "Delete Pole?",
            "ok_text": "Okay",
            "dismiss_text": "Cancel"
          }
        }`

**Comment by caiceA** [comment]
this is not what I need to fix that issue can you get the class?

**Comment by kayran** [comment]
I used the polly  app to create a poll and it has a danger button to delete the poll. This button has background and text white

![image](https://user-images.githubusercontent.com/474481/63125303-b7654880-bf83-11e9-9e33-e9bea99c1030.png)

**Comment by caiceA** [comment]
i can't find that button @kayran  if you can inspect the css let me know 

<img width="1292" alt="Screenshot 2019-08-15 at 23 17 21" src="https://user-images.githubusercontent.com/16766231/63130601-e7781000-bfb2-11e9-9d61-d4800b34e581.png">
<img width="441" alt="Screenshot 2019-08-15 at 23 17 36" src="https://user-images.githubusercontent.com/16766231/63130602-e7781000-bfb2-11e9-9621-cdf340137f91.png">

**Comment by caiceA** [comment]
I think it's on Linux because my mac side the delete / Close / Cancel button has small **X** sign on top right

**Comment by kayran** [comment]
this button only appears after the polly created, as you can see, on mac the close are different, and you cant reproduce it.

**Comment by caiceA** [comment]
are you using linux?

**Comment by kayran** [comment]
Yes @caiceA, i'm using Manjaro Linux.
