### ISSUE TITLE
Drag and Drop .sh file

### ISSUE THREAD

**Issue by redshadeaux** [caiceA/slack-black-theme#67]
I am not seeing any change in Slack after I drag and drop the .sh file into my Mac's terminal and executing it. I have node and npm installed as shown in the screenshots. I also attached what I see after I execute the .sh file. What am I missing?
<img width="297" alt="Screen Shot 2019-07-18 at 1 13 09 AM" src="https://user-images.githubusercontent.com/53033631/61433581-4a658100-a8f9-11e9-9733-9b41fb7f07d0.png">
<img width="630" alt="Screen Shot 2019-07-18 at 1 13 23 AM" src="https://user-images.githubusercontent.com/53033631/61433583-4b96ae00-a8f9-11e9-836e-617fe75b6a67.png">

**Comment by caiceA** [comment]
try running this command first then drag and drop 

npm i -g asar

**Comment by redshadeaux** [comment]
Did that and after running the .sh file, it says I need to enter a password but never gives me the prompt to do so like it did before. I also tried running the .sh file with sudo in front.
<img width="475" alt="Screen Shot 2019-07-18 at 2 03 15 AM" src="https://user-images.githubusercontent.com/53033631/61436426-5f91de00-a900-11e9-8e9b-240c817e55bc.png">
<img width="630" alt="Screen Shot 2019-07-18 at 2 03 25 AM" src="https://user-images.githubusercontent.com/53033631/61436427-5f91de00-a900-11e9-8942-0e6794208fbb.png">

**Comment by brentmwarner** [comment]
I'm also doing all of these on linux and it's not working. Any help on this?

**Comment by caiceA** [comment]
when it says provide password just start typing the password without waiting on anything and after you finish typing password press enter

**Comment by caiceA** [comment]
check readme file and i am attaching the .sh file its working fine on my side 

[slack-dark-mode.sh (2).zip](https://github.com/caiceA/slack-black-theme/files/3487268/slack-dark-mode.sh.2.zip)

**Comment by brentmwarner** [comment]
I'm not sure what's going on then. I've literally done everything in the readme. Screen grab attached below.

**Comment by brentmwarner** [comment]
I've also checked the root and there's no file called ssb-interop.bundle.js not sure if that's a version 4.0.1 thing

**Comment by caiceA** [comment]
remove your slack and download new version 4.0.2

**Comment by brentmwarner** [comment]
Got it I'll try that

**Comment by brentmwarner** [comment]
version 4.0.2 is only availale for mac. I'm runnning linux (ubuntu) so I'm not sure if that's the issue.
