### ISSUE TITLE
Different styling

### ISSUE THREAD

**Issue by alanjc7** [caiceA/slack-black-theme#68]
Not sure if this is an issue or the expected behaviour (please close if so!).
After installing the theme, I think it looks slightly different from your screenshots, although its quite hard to tell. 

The pictures below show the unread channel font/highlighting and the font. Do these look as expected?

<img width="210" alt="unread" src="https://user-images.githubusercontent.com/22035954/61446430-0731ff00-a947-11e9-9704-f727fed28181.png">
<img width="425" alt="font" src="https://user-images.githubusercontent.com/22035954/61446437-08fbc280-a947-11e9-9947-9a82b7d3f32a.png">

**Comment by caiceA** [comment]
Yes you have the latest one mockups are old and the fonts in mockups are different ( old )

**Comment by caiceA** [comment]
Your fonts are slightly different I think not as per the theme ( new ). But styling is the same

**Comment by caiceA** [comment]
<img width="229" alt="Screenshot 2019-07-18 at 13 29 04" src="https://user-images.githubusercontent.com/16766231/61454051-0eb1d200-a960-11e9-9826-c8f40b615e71.png">

**Comment by caiceA** [comment]
I would suggest you, remove the Slack and have fresh install then the theme

**Comment by alanjc7** [comment]
Yeah, that's what I thought. Your font looks much better!

Fresh install didn't work but don't worry, it's clearly a localised issue so feel free to close this.
Thanks for the quick response!

**Comment by caiceA** [comment]
@alanjc7 

Download and install this font 

https://www.fontsquirrel.com/fonts/download/muli

**Comment by alanjc7** [comment]
Thanks @caiceA - that solved it!
