### ISSUE TITLE
Lato font back in v4?

### ISSUE THREAD

**Issue by jonasmellquist** [caiceA/slack-black-theme#69]
Hi - is it possible to have the Lato font back for Slack v4 Mac?

The default font is pretty awful / boring 👎 

-Jonas

**Comment by caiceA** [comment]
this is not an issue, this is how the theme is designed. Thanks

**Comment by ikunali** [comment]
Ya, the default slack v4 font sucks. Wish we could have a better font.

**Comment by caiceA** [comment]
I hate Lato

**Comment by caiceA** [comment]
@TG-KK @jonasmellquist can you guys send me a screenshot of what font you guys are seeing in the app?

**Comment by caiceA** [comment]
Download and install this font 

https://www.fontsquirrel.com/fonts/download/muli

**Comment by ikunali** [comment]
This is how it looks: 

<img width="1700" alt="image" src="https://user-images.githubusercontent.com/6836944/61657619-5fdc0180-ac91-11e9-92f4-a39360cda416.png">

**Comment by caiceA** [comment]
what is this shit 

you install the above font than restart your computer

**Comment by caiceA** [comment]
https://user-images.githubusercontent.com/16766231/61454517-68ff6280-a961-11e9-9a2b-aa929fb649c5.png

 this is how it should look
