### ISSUE TITLE
bolder "unreads" in channel sidebar?

### ISSUE THREAD

**Issue by nhaines-zen** [caiceA/slack-black-theme#7]
I love this theme, but one issue I'm having is that I can't really tell when a channel has unread messages (but not a badge) - you can just barely tell it's bolded. Do you know which line I can change to make this text bolder/larger?

**Comment by caiceA** [comment]
@nhaines-zen 
Add this CSS at the bottom, I added further indicator red border to looks more clear when unread message in channel for example channel name **Engineering** 

.p-channel_sidebar__channel--unread:not(.p-channel_sidebar__channel--muted):not(.p-channel_sidebar__channel--selected) .p-channel_sidebar__name, .p-channel_sidebar__link--unread .p-channel_sidebar__name, .p-channel_sidebar__link--invites:not(.p-channel_sidebar__link--dim) .p-channel_sidebar__name{
    border-left: 2px solid #ff5656;
    padding-left: 6px;
    height: 20px;
    overflow: hidden;
    line-height: 16px;
    font-size: 17px;
}

<img width="232" alt="screenshot 2018-10-01 at 23 40 42" src="https://user-images.githubusercontent.com/16766231/46317506-79616f00-c5d3-11e8-8471-53f15076429f.png">
