### ISSUE TITLE
Missing Directory Structure in latest Slack update

### ISSUE THREAD

**Issue by omnilord** [caiceA/slack-black-theme#72]
MacOS Mojave Version 10.14.5
Slack Version 4.0.0 (App Store)

I updated Slack this morning, and went to re-up my theme but the shell script as written doesn't work `/Applications/Slack.app/Contents/Resources/app.asar.unpacked/src` is not present in the Slack update I received this morning.

I created the directory with `mkdir -p /Applications/Slack.app/Contents/Resources/app.asar.unpacked/src/static` then put ssb-interop.js in there, but this does not apply the theme any longer.

**Comment by caiceA** [comment]
I think if you update slack that won't work but if you remove the slack and download new from a website and then install the theme **as per instruction** it should work

close the issue later

**Comment by omnilord** [comment]
Oooooh boy, that's a whole new process.  Was _not_ expecting that.  Gotcha.  :thumb

**Comment by omnilord** [comment]
Out of curiosity, why haven't you updated the blackSlack.sh in this repo with the other shell script?

**Comment by caiceA** [comment]
I actually removed all the files in the repo. simple drag and drop and restart this is a more easy process to me (:
