### ISSUE TITLE
Running on Linux

### ISSUE THREAD

**Issue by tylermanning** [caiceA/slack-black-theme#74]
This nearly works on Linux. I updated the bash script to match where Linux stores the files:
`
SLACK_RESOURCES_DIR="/usr/lib/slack/resources"
SLACK_FILE_PATH="${SLACK_RESOURCES_DIR}/app.asar.unpacked/dist/ssb-interop.bundle.js"
`

 I can then run the bash script and the colors update but to a harsher contrast that is not what your images show. Any idea why? 
![image](https://user-images.githubusercontent.com/16857213/61661862-24463500-ac9b-11e9-9f3c-f884a2ad3d0a.png)

Also, if I try editing the colors for a different set, it never updates again and stays on this high contrast black setting.

**Comment by caiceA** [comment]
because you can not update the colors if you are running local path you can. 
also you need to install the font as  per readme

**Comment by tylermanning** [comment]
I don't know what you mean by this sentence:

> because you can not update the colors if you are running local path you can.

And You're right I forgot to install the fonts. How do I install them?

**Comment by chuyaguo2014** [comment]
the link to the fonts is in the readme. 

![image](https://user-images.githubusercontent.com/9753313/61663358-72a90300-ac9e-11e9-9543-6fff10780bff.png)

**Comment by caiceA** [comment]
you download the font from this  link and install them in  your computer 
i never used linux you can google it how to install on linux. 

**because you can not update the colors if you are running local path you can**. this means you can not edit colors because the CSS URL is online. if you running CSS in your local path only then you can make edit and see it

for the script you can find something from here [in this  issue](https://github.com/widget-/slack-black-theme/issues/98)

**Comment by tylermanning** [comment]
Okay I installed the .ttf fonts on Linux. It is easy: https://vitux.com/how-to-install-truetype-fonts-in-ubuntu/

I also reinstalled Slack to start fresh. I want to rerun your theme installer again but I am scared I won't be able to revert without having to uninstall /reinstall Slack again. Is there a simple way to revert if the colors are bad again?

**Comment by caiceA** [comment]
the script in this repo is only for MAC I gave you other issue in my previous comment for Linux + Windows, your solution is there not here in my .sh file

**Comment by tylermanning** [comment]
So I reran the bash script on Linux even though you don't recommend it and it seems to give the correct output. The fonts helped for sure. I think the CSS you have just doesn't render the same on Linux compared to Mac. I'll try to find some CSS that is similar for Linux and post if I can.

**Comment by caiceA** [comment]
The script has a link of the CSS used for this theme you can download it

**Comment by tylermanning** [comment]
Thanks. I downloaded but it's over 2000 lines long. I don't know where to begin editing it. Any tips?
I just want to have a basic dark theme similar to one-dark here: https://github.com/widget-/slack-black-theme

**Comment by caiceA** [comment]
i fixed this issue
