### ISSUE TITLE
Manual update with 7zip not working (Windows)

### ISSUE THREAD

**Issue by knwpsk** [caiceA/slack-black-theme#80]
Windows user.
Can't install Nodejs (without admin), so I updated ssb-interop manually using 7zip, as discussed in another repo.  This worked fine with the caiceA/slack-raw version, but I can't get it working with this version.  

Details:
I opened  slack-dark-mode.sh, copied the JS string, and pasted it at the end of ssb-interop.bundle.js (using 7zip > open archive > view), saved and repacked.

I can't see any substantial difference between what's in the JS string here, vs what was in the other version.  So why doesn't this work?  What am I missing?

**Comment by caiceA** [comment]
well i am not sure about windows its for Mac
