### ISSUE TITLE
Popped out posts have white background and are unreadable

### ISSUE THREAD

**Issue by thom-nic** [caiceA/slack-black-theme#81]
On slack for macOS, v 4.0.0.  Create a post, share in a channel, the click the button that says "Edit in new window":

![Screen Shot 2019-07-26 at 10 47 33 AM](https://user-images.githubusercontent.com/95562/61960106-e135db80-af92-11e9-901c-2fbd40cb1a34.png)

Interestingly, there's a `light_theme` class applied but I don't see any styles associated with it.

**Comment by thom-nic** [comment]
This is what it should look like: (except dark)
![Screen Shot 2019-07-26 at 10 52 09 AM](https://user-images.githubusercontent.com/95562/61960442-776a0180-af93-11e9-9411-7cee615bec9d.png)

**Comment by thom-nic** [comment]
No fix?  I just re-installed and restarted slack.app:
![Screen Shot 2019-08-01 at 2 19 49 PM](https://user-images.githubusercontent.com/95562/62317349-7d665380-b467-11e9-8608-41820f5767c3.png)
😢

**Comment by caiceA** [comment]
i think i made the half fixing 
send me content you are using here i will test and fix

**Comment by thom-nic** [comment]
Let me see if I can debug.  It's a little more difficult due to the asar re-packing.

**Comment by caiceA** [comment]
send met the content only, the bullet points  etc

**Comment by thom-nic** [comment]
```
This is a test
\```
it's no very long
\```
* [_] Just a couple
* [_] items
## Heading 2
### Heading 3
* Bullet
* points with `inline code`
```
