### ISSUE TITLE
Creating a Windows Compatible Version 

### ISSUE THREAD

**Issue by benjamhooper** [caiceA/slack-black-theme#82]
Started the process of creating a powershell script for automatic install on windows. Currently I have it to where you only need to know the version you are on. 

By going to  Help -> About Slack. 
![image](https://user-images.githubusercontent.com/6244607/61988283-ef144c80-afe4-11e9-927a-1ae1ffab108d.png)

Mind if I create a pull request when finished?

**Comment by caiceA** [comment]
Yes i can merge

**Comment by matt1981m** [comment]
If you would like a guinea pig to test it out, I volunteer myself as tribute!!!
