### ISSUE TITLE
Ended call grey on grey text

### ISSUE THREAD

**Issue by JeanRessouche** [caiceA/slack-black-theme#87]
Slack v4.0.1, Windows.

When a call is ended, this stack is added in the source channel.
The text color (here in French, sorry for that) "You and ..... joined the call" isn't easy to read.

![image](https://user-images.githubusercontent.com/8854025/62291822-2c556000-b465-11e9-85e0-7cd0da5a2f98.png)

**Comment by caiceA** [comment]
i run free version, i don't have calls access

**Comment by caiceA** [comment]
fixed
