### ISSUE TITLE
please consider adding option for just changing the color scheme

### ISSUE THREAD

**Issue by juchoe** [caiceA/slack-black-theme#88]
While I love the customized fonts and other changes you've made, I also think it would be great if there was an option to leave everything as is but just change the color scheme for the dark mode. 

Thank you for your great work!

**Comment by caiceA** [comment]
What you mean change the dark mood with additional dark theme

**Comment by chrisharrisonkiwi** [comment]
Just update the colours I reckon.
That font is not even remotely Slack friendly.

**Comment by juchoe** [comment]
yeah, I meant just update the colors like chrisharrisonkiwi said.

**Comment by caiceA** [comment]
will try some day
