### ISSUE TITLE
/shrug not displaying properly 

### ISSUE THREAD

**Issue by MyGitUsrname** [caiceA/slack-black-theme#90]
Version 4.0.1 (App Store) 
MacOS 10.14.5

What it should look like
<img width="121" alt="Shrug normal" src="https://user-images.githubusercontent.com/22553515/62584081-2f3dce00-b907-11e9-95a1-3298a6e4aa52.png">

What it shows for me 
<img width="123" alt="Shrug not normal" src="https://user-images.githubusercontent.com/22553515/62584093-411f7100-b907-11e9-90f2-444428ac1bde.png">

**Comment by caiceA** [comment]
Attach better img with full details of issue

**Comment by MyGitUsrname** [comment]
/shrug is a command that adds the shrug emoji to the end of your message.

i.e if you type "/shrug my message here" it will show "my message here ¯\\\_(ツ)\_/¯"

it should be displayed as ¯\\\_(ツ)\_/¯
but with your theme the text is still ¯\\\_(ツ)\_/¯ but it gets displayed as <img width="192" alt="bad slack shrug" src="https://user-images.githubusercontent.com/22553515/63398516-00a11680-c422-11e9-9b22-0d5e914f4fdd.png">
