### ISSUE TITLE
Warning popup is white text on white background

### ISSUE THREAD

**Issue by bisen2** [caiceA/slack-black-theme#94]
Slack linux client v 4.0.1

When trying to address a channel with `@channel`, a warning pops up. This popup seems to not be themed and has white on white text.

Steps to reproduce:
Type `@channel test` in message bar and hit enter.

![slack_warning_message](https://user-images.githubusercontent.com/39412411/62668945-b87ef000-b95b-11e9-96f0-a679e529de3b.png)

**Comment by caiceA** [comment]
@bisen2 thanks for this issue, 
it's fixed please restart

**Comment by bisen2** [comment]
@caiceA using the latest css and reinstalling I still see this issue.

**Comment by caiceA** [comment]
I am using a mac, I fixed this on a Mac I am not 100% sure why it's not reflecting on your side. Maybe after sometime
