### ISSUE TITLE
@channel alert unreadable

### ISSUE THREAD

**Issue by Steve24959** [caiceA/slack-black-theme#95]
**Describe the bug**
When mentioning @channel the text on the dialog is unreadable. This may be related to #81

**To Reproduce**
1. Make @channel announcement.

**Expected behavior**
Alert box matches theme.

**Screenshots**
![Screen Shot 2019-08-09 at 7 55 29 AM](https://user-images.githubusercontent.com/53942299/62780865-4520cf80-ba7c-11e9-9dc1-6b506371d6f6.png)

**Desktop (please complete the following information):**
 - OS: Mojave 10.14.4

**Comment by caiceA** [comment]
its already done
