### ISSUE TITLE
I am receiving this error, any idea as to how fix this?

### ISSUE THREAD

**Issue by KTsarlz** [caiceA/slack-black-theme#96]
Exception calling "DownloadString" with "1" argument(s): "Unable to connect to the remote server"
At line:1 char:1
+ iex (new-object net.webclient).downloadstring('https://raw.githubuser ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

**Comment by KTsarlz** [comment]
Hello @caiceA sorry, but how was this resolved? Was there an update made to the code? Or any changes I need to this machine?

**Comment by caiceA** [comment]
i closed you issue because you didn't follow the issue creating pattern properly
