### ISSUE TITLE
Can toaster notifications be modified?

### ISSUE THREAD

**Issue by knwpsk** [caiceA/slack-black-theme#98]
I think the new toaster popup notifications suck (since Slack 4.x).  They're too big, gaudy, and don't have enough text.  
Could we modify the font/size with this CSS hack?  I'm not great at CSS so I haven't found a way to do it on my own.
Appreciate any help.

**Comment by caiceA** [comment]
Follow the issue pattern, and re-create this

**Comment by knwpsk** [comment]
@caiceA sorry, are you saying change the type of ticket from bug to something else?  When I click "get started" in this project, the only choice it shows is "bug".

**Comment by caiceA** [comment]
Hi,
yes I created another template(s) please use them if possible attach something / photos etc

**Comment by knwpsk** [comment]
ok thanks.  I resubmitted as a feature req.
