### ISSUE TITLE
Can we modify the toaster popup notification?

### ISSUE THREAD

**Issue by knwpsk** [caiceA/slack-black-theme#99]
I think the new toaster popup notifications suck (since Slack 4.x). They're too big, gaudy, and don't have enough text.
Could we modify the font/size with this CSS hack? I'm not great at CSS so I haven't found a way to do it on my own.
Appreciate any help.

![image](https://user-images.githubusercontent.com/30087322/63033953-7c311f80-be86-11e9-9fc8-ed7ac873a238.png)

**Comment by benjamhooper** [comment]
I use "Windows Action Center" to circumvent that. 

![image](https://user-images.githubusercontent.com/6244607/63048987-4c414680-be9d-11e9-9a1a-2c49c7704727.png)

Though if you'd like that customized we'd have to look if notifications fit into main theme or a different file.

**Comment by caiceA** [comment]
@knwpsk i see its for windows... i don't think i can check this because i don't have Windows but see @benjamhooper can help you on this

**Comment by knwpsk** [comment]
Yes i'm on windows.  Assumed the css is the same regardless -- that is, if it's even possible to modify the format of the toasters using the css...  
If not, close this, it's not a big deal.

I noticed when I get a toaster, I right-click > Inspect Element, and it does go to a spot in the css very briefly... but then the toaster goes away, and the element inspector scrolls, so it's really hard to trace.
And I'm a noob at css anyway.

**Comment by caiceA** [comment]
i never used windows so i don't have anything to check / inspect ATM
